name: CityBuildSystem
main: de.wichtigesyt.Main
version: 1.6

commands:
  delhome:
  home:
  homes:
  sethome:
  delwarp:
  setwarp:
  warp:
  warps:
  chatblock:
  clearchat:
  clear:
  ec:
  fly:
  gm:
  invsee:
  msg:
  r:
  money:
  money-admin:
  pay:
  tpa:
  tpadeny:
  tpaccept:
  hat:
  tp:
  premium:
  spawn:
  setspawn:
  tpall:
  belohnung:
  v:
  tpahere:
  tphere:
  kopf:
  speed:
  perks:
  heal:
  repair:
  pmute:
  slowchat:
  startkick:
  ja:
  nein:
  rename: